/* 2. Crea un programa que pregunte al usuario un número. Usando el archivo de arreglo de Pokémons, mostrar solo los nombres de los Pokémons cuyos números que son múltiplos de 5 desde 1 hasta el número introducido por el usuario. */

const pokemon = [
    { name: "Bulbasaur", number: 1 },
    { name: "Ivysaur", number: 2 },
    { name: "Venusaur", number: 3 },
    { name: "Charmander", number: 4 },
    { name: "Charmeleon", number: 5 },
    { name: "Charizard", number: 6 },
    { name: "Squirtle", number: 7 },
    { name: "Wartortle", number: 8 },
    { name: "Blastoise", number: 9 },
    { name: "Caterpie", number: 10 },
    { name: "hiedrosaurio", number: 11 },
    { name: "encantador", number: 12 },
    { name: "metapod", number: 13 },
    { name: "butterfree", number: 14 },
    { name: "weedle", number: 15 },
    { name: "kakuna", number: 16 },
    { name: "beedrill", number: 17 },
    { name: "pidgey", number: 18 },
    { name: "pidgeotto", number: 19 },
    { name: "pidgeot", number: 20 },
    { name: "rattata", number: 21 },
    { name: "raticate", number: 22 },
    { name: "spearow", number: 23 },
    { name: "fearow", number: 24 },
    { name: "ekans", number: 25 },
    { name: "arbok", number: 26 },
    { name: "pikachu", number: 27 },
    { name: "raichu", number: 28 },
    { name: "sandshrew", number: 29 },
    { name: "sandslash", number: 30 },
    { name: "nidoran", number: 31 },
    { name: "nidorina", number: 32 },
    { name: "nidoqueen", number: 33 },
    { name: "nidoran-m", number: 34 },
    { name: "nidorino", number: 35 },
    { name: "nidoking", number: 36 },
    { name: "clefairy", number: 37 },
    { name: "clefable", number: 38 },
    { name: "vulpix", number: 39 },
    { name: "ninetales", number: 40 },
    { name: "jigglypuff", number: 41 },
    { name: "wigglytuff", number: 42 },
    { name: "zubat", number: 43 },
    { name: "golbat", number: 44 },
    { name: "oddish", number: 45 },
    { name: "gloom", number: 46 },
    { name: "vileplume", number: 47 },
    { name: "paras", number: 48 },
    { name: "parasect", number: 49 },
    { name: "venonat", number: 50 },
    { name: "venomoth", number: 51 },
    { name: "diglett", number: 52 },
    { name: "dugtrio", number: 53 },
    { name: "meowth", number: 54 },
    { name: "persian", number: 55 },
    { name: "psyduck", number: 56 },
    { name: "golduck", number: 57 },
    { name: "mankey", number: 58 },
    { name: "primeape", number: 59 },
    { name: "growlithe", number: 60 },
    { name: "arcanine", number: 61 },
    { name: "poliwag", number: 62 },
    { name: "poliwhirl", number: 63 },
    { name: "poliwrath", number: 64 },
    { name: "abra", number: 65 },
    { name: "kadabra", number: 66 },
    { name: "alakazam", number: 67 },
    { name: "machop", number: 68 },
    { name: "machoke", number: 69 },
    { name: "machamp", number: 70 },
    { name: "bellsprout", number: 71 },
    { name: "weepinbell", number: 72 },
    { name: "victreebel", number: 73 },
    { name: "tentacool", number: 74 },
    { name: "tentacruel", number: 75 },
    { name: "geodude", number: 76 },
    { name: "graveler", number: 77 },
    { name: "golem", number: 78 },
    { name: "ponyta", number: 79 },
    { name: "rapidash", number: 80 },
    { name: "slowpoke", number: 81 },
    { name: "slowbro", number: 82 },
    { name: "magnemite", number: 83 },
    { name: "magneton", number: 84 },
    { name: "farfetchd", number: 85 },
    { name: "doduo", number: 86 },
    { name: "dodrio", number: 87 },
    { name: "seel", number: 88 },
    { name: "dewgong", number: 89 },
    { name: "grimer", number: 90 },
    { name: "muk", number: 91 },
    { name: "shellder", number: 92 },
    { name: "cloyster", number: 93 },
    { name: "gastly", number: 94 },
    { name: "haunter", number: 95 },
    { name: "gengar", number: 96 },
    { name: "onix", number: 97 },
    { name: "drowzee", number: 98 },
    { name: "hypno", number: 99 },
    { name: "krabby", number: 100 },
    { name: "kingler", number: 101 },
    { name: "voltorb", number: 102 },
];

const numero = parseInt(prompt("Ingrese un número"));

for (let i = 1; i <= numero; i++) {
    if (i % 5 === 0) {
        const pokemonMultiploDe5 = pokemon.find(pokemon => pokemon.number === i);
        if (pokemonMultiploDe5) {
            document.write(pokemonMultiploDe5.name + ", ");
        }
    }
}